### ISSUE TITLE
Doesn't check for ! adjacent to variable name

### ISSUE THREAD

**Issue by lewilewilewi** [djoos/Symfony2-coding-standard#29]
As the code standard says:
Place unary operators (!, --, ...) adjacent to the affected variable;

This isn't currently detected.

**Comment by wickedOne** [comment]
hi @lewilewilewi
you're right, there currently are several sniffs missing from this standard as listed [here](https://github.com/djoos/Symfony2-coding-standard/issues/66). we'll be working on adding as much of these as possible; feel free to contribute!
