### ISSUE TITLE
Installation directory

### ISSUE THREAD

**Issue by aRn0D** [djoos/Symfony2-coding-standard#48]
Hi here,

I tried to install this library with command `composer require --dev escapestudios/symfony2-coding-standard:~2.0` . It should be installed in the `vendor/escapestudios/symfony2-coding-standard` like it is explained in the readme but it installed in `vendor/escapestudios/symfony2-coding-standard/escapestudios/Symfony2-coding-standard`. FYI, I am using the latest version of composer. 

What happened? Did I do something something wrong?

Thank you.

**Comment by phoenixgao** [comment]
@aRn0D what's in your main project's composer.json?

**Comment by djoos** [comment]
Hi @aRn0D,

are you still experiencing this issue?

Thanks in advance for your feedback!

Kind regards,
David

**Comment by aRn0D** [comment]
I can't reproduce this issue because we changed our CI and we don't use this lib anymore.
