### ISSUE TITLE
Current sniffs

### ISSUE THREAD

**Issue by wickedOne** [djoos/Symfony2-coding-standard#64]
As suggested in #32, i think it would be good to have some kind of list indicating which standards are already enforced by this repo and which still need to be done. 

this not only makes it easier for contributors to find a sniff they can work on, but also to see which new standards have been added [to the Symfony standards page](http://symfony.com/doc/current/contributing/code/standards.html) as that list appears to be changing quite a bit.

opening a seperate issue for each missing sniff might clutter the issues list so i'd like to propose grouping them like they are grouped on Symfony's standards page. which could look like something like this:

#### [Structure](http://symfony.com/doc/current/contributing/code/standards.html#structure)

- [x] Add a single space after each comma delimiter;
- [x] Add a single space around binary operators (==, &&, ...), with the exception of the concatenation (.) operator;
- [ ] Place unary operators (!, --, ...) adjacent to the affected variable;
- [ ] Always use identical comparison unless you need type juggling;
- [ ] Use Yoda conditions when checking a variable against an expression to avoid an accidental assignment inside the condition statement (this applies to ==, !=, ===, and !==);
- [x] Add a comma after each array item in a multi-line array, even after the last one;
- [x] Add a blank line before return statements, unless the return is alone inside a statement-group (like an if statement);
- [ ] Use return null; when a function explicitly returns null values and use return; when the function returns void values;
- [x] Use braces to indicate control structure body regardless of the number of statements it contains;
- [x] Define one class per file
- [ ] Declare the class inheritance and all the implemented interfaces on the same line as the class name;
- [x] Declare class properties before methods;
- [x] Declare public methods first, then protected ones and finally private ones. The exceptions to this rule are the class constructor and the setUp() and tearDown() methods of PHPUnit tests, which must always be the first methods to increase readability;
- [ ] Declare all the arguments on the same line as the method/function name, no matter how many arguments there are;
- [x] Use parentheses when instantiating classes regardless of the number of arguments the constructor has;
- [ ] Exception and error message strings must be concatenated using sprintf;
- [ ] Calls to trigger_error with type E_USER_DEPRECATED must be switched to opt-in via @ operator. 
- [ ] Do not use else, elseif, break after if and case conditions which return or throw something;
- [ ] Do not use spaces around [ offset accessor and before ] offset accessor.

and perhaps to clarify include an example for each rule which should trigger an error, e.g.

```php
<?php
    // Add a single space after each comma delimiter;
    function foo($a,$b){}
    
    // Add a single space around binary operators
    if ($a==$b){}
    
    // Place unary operators adjacent to the affected variable
    $a = $b++;
    
    // Always use identical comparison
    if ($a == $b) {}
    
    // Use Yoda conditions
    if ($a == 1) {}
    
    // Add a comma after each array
    $a = [
        'foo',
        'bar'
    ];
    
    // Add a blank line before return statements
    function foo()
    {
        $a = $b;
        return $b;
    }
    
    // ... etc
```

any thoughts on this?

**Comment by djoos** [comment]
This is a brilliant suggestion - perfectly in line with the frustration of #32!

**Comment by wickedOne** [comment]
excellent! 
i'll open a couple of issues this weekend listing the snifss already implemented and those which still need to be done and include a class from hell which should trigger all of the mentioned standards in order for the issue to be resolved
