### ISSUE TITLE
changing standard name from symfony2 to symfony?

### ISSUE THREAD

**Issue by wickedOne** [djoos/Symfony2-coding-standard#65]
as i was working on the [phpcs 3 compatibility issue](https://github.com/djoos/Symfony2-coding-standard/pull/63) i wondered whether it would be an idea to change the standard name from ``Symfony2`` to ``Symfony`` as obviously this standard isn't bound to any version of symfony and might cause confusion in the foreseeable future as the release of Symfony 4 is scheduled for this year... (and basically a major each year thereafter)

any thoughts?

**Comment by djoos** [comment]
Great spot - definitely the way forward!

**Comment by djoos** [comment]
I'm keen on getting the 3.x PR merged in ASAP, as dev-master, and then we will worry about rewire the naming as part of additional refactoring, until we're happy and can push out 3.0.0.

What do you think?

**Comment by wickedOne** [comment]
yes i completely agree.
it will also have effect on ruleset definitions (e.g. ``<rule ref="Symfony2.Commenting.ClassComment.SpacingBeforeTags">``) so we might want to consider to add a little upgrade guide for those who use custom rulesets...

**Comment by djoos** [comment]
Agreed!

We do need to give this some proper thought, however: if we have to do this, the main version bump (3.x) is a great place to do it...

FYI: I'm off for a week, sorry if I don't get back - I'll pick things back up when I'm back!

**Comment by wickedOne** [comment]
yes let's do so!
thanks for the heads up!
